#!/usr/bin/python

import dbus
import sys

bus = dbus.SessionBus()

if len(sys.argv) < 2:
	print "Usage: get-all-meta-session key [imsi]\n"
	System.Exit(1)

if len(sys.argv) < 3:
	imsi = ""
else:
	imsi = sys.argv[2];


manager = dbus.Interface(bus.get_object('com.intel.provman.server', '/com/intel/provman'),
					'com.intel.provman.Settings')
manager.Start(imsi)
settings =  manager.GetAllMeta(sys.argv[1])
for i in settings:
	print i[0] + "?" + i[1] + " = " + i[2] 
manager.End()
