#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) < 2:
	print "Usage: get-ti-children-system key\n"
	sys.exit(1)

key = sys.argv[1]

manager = dbus.Interface(bus.get_object('com.intel.provman.server', '/com/intel/provman'),
					'com.intel.provman.Settings')
try:
    settings = manager.GetChildrenTypeInfo(key)
    keys = sorted(settings.keys())
    for key in keys:
	    print key + " ( " + settings[key] + " )"

except dbus.exceptions.DBusException:
    print("Unable to retrieve type information for : " + key)
    pass
